### PR TITLE
Swagger Docs

### PR DESCRIPTION
**Pull request by runabol**
Based on PR https://github.com/runabol/tork/pull/133

* Adds a `Makefile` command to update the swag docs.
* Adds the /swagger endpoint to serve the swagger docs.

### CODE REVIEW

**Comment by runabol** [comment]
@networkinss thoughts?

**Comment by runabol** [comment]
I'm not crazy at all at how much it bloats the build size though:

```shell
19M Sep 11 16:49 tork
```
vs.

```shell
 29M Sep 11 16:49 tork
```
Trying to think of alternatives

**Comment by runabol** [comment]
OK, I think I managed to figure it out. I plan on [using docker](https://github.com/runabol/tork/pull/139/commits/e028d03fbbf460cee4cc7436ffa76abcbe7dfda9#diff-3fde9d1a396e140fefc7676e1bd237d67b6864552b6f45af1ebcc27bcd0bb6e9R18-R26) to serve the `swag` tool output.

**Comment by networkinss** [comment]
I think to show the Swagger UI you can integrate the original from Smartbear:
https://swagger.io/tools/swagger-ui/
It is made to show a UI for an openapi document.

Alternative is https://redocly.com/, which is more sophisticated, but just to show a UI the Swagger UI is nicer.

**Comment by runabol** [comment]
> I think to show the Swagger UI you can integrate the original from Smartbear: https://swagger.io/tools/swagger-ui/ It is made to show a UI for an openapi document.
> 
> Alternative is https://redocly.com/, which is more sophisticated, but just to show a UI the Swagger UI is nicer.

Yep, that's what I'm doing by using the docker image: https://hub.docker.com/r/swaggerapi/swagger-ui

**Comment by runabol** [comment]
@networkinss thanks very much for your help!

**Comment by networkinss** [comment]
What about let the backend serve only the swagger.json content and let the web-ui show the Swagger UI ?
Swagger UI can be easily integrated as static files: https://stackoverflow.com/questions/46237255/how-to-embed-swagger-ui-into-a-webpage

**Comment by runabol** [comment]
@networkinss that's exactly right. that's basically what it does. 

The [Makefile](https://github.com/runabol/tork/blob/e6562429af211dd7ce0c4c5531598f83c5e01691/Makefile#L24-L27) is used for generating the `swagger.json` file based on the annotations you added using the swagger CLI. And then the [docker container](https://github.com/runabol/tork/blob/e6562429af211dd7ce0c4c5531598f83c5e01691/docker-compose.yaml#L18-L26) is used for rendering the JSON.

**Pull request merged**
