### PR TITLE
Add support for matrix strategy during GitHub Workflows

### PR DESCRIPTION
**Pull request by gaby**
- Add support for Matrix Strategy Tests
- Add support for testing against latest 3 releases of Golang
- Add support for testing against latest 2 major versions of Postgres
- Cleanup old dependencies from go.mod/go.sum files
- Add support for not running the CI jobs when changes to `.MD` files are detected.
- Add `-race` to detect race conditions during CI jobs.

### CODE REVIEW

**Comment by gaby** [comment]
@runabol Running the tests with `-race` found several race conditions, were you aware of those?

**Comment by runabol** [comment]
> @runabol Running the tests with `-race` found several race conditions, were you aware of those?

@gaby  Interesting. I'm on it.

**Comment by gaby** [comment]
@runabol I merged your recent changes but it will found race conditions across several modules

**Comment by runabol** [comment]
@gaby yep, still a work in progress. Should be done soon.

**Comment by gaby** [comment]
@runabol I noticed there's quite a bit of custom concurrency in Tork, have you heard about `conc` by sourcegraph? 

https://github.com/sourcegraph/conc

**Comment by runabol** [comment]
> @runabol I noticed there's quite a bit of custom concurrency in Tork, have you heard about `conc` by sourcegraph?
> 
> https://github.com/sourcegraph/conc

@gaby I never heard of `conc` but I'll definitely take a look. But in these cases it was really my silly use of state in several places. 

In any event, all data race related issues should be fixed now. Thanks for calling this out. Super helpful.

**Comment by gaby** [comment]
@runabol Looks better! There's only two Data Race detected errors now. One in the memory test, one in the postgres concurrent test

**Comment by runabol** [comment]
> @runabol Looks better! There's only two Data Race detected errors now. One in the memory test, one in the postgres concurrent test

@gaby 

> @runabol Looks better! There's only two Data Race detected errors now. One in the memory test, one in the postgres concurrent test



> @runabol Looks better! There's only two Data Race detected errors now. One in the memory test, one in the postgres concurrent test

@gaby yep looks like I missed a couple. mind rebasing and trying again?

**Comment by runabol** [comment]
@gaby looks like it passed! Do you mind rebasing your PR down to a single commit? This will ensure a nice clean Git history.

**Comment by gaby** [comment]
@runabol I'm on my phone right now, but you should be able to do that on GitHub. In the "Merge" button there should be an arrow with a dropdown, that dropdown has a "Squash and Merge" option.

**Comment by runabol** [comment]
@gaby Done. Really nice PR. Thank you!

**Pull request merged**
